import { Client } from 'dagpijs';
import { NextApiRequest, NextApiResponse } from 'next';

export default async (req: NextApiRequest, res: NextApiResponse) => {
    const body = JSON.parse(req.body);
    let dc;
    try {
        if (body.token) {
            dc = new Client(body.token);
        } else {
            dc = new Client(process.env.DAGPI_TOKEN);
        }
        const json = await dc[body.method]();
        res.send({
            json: json
        });
    } catch (error) {
        res.send({
            response: error.toString(),
            status: error.status,
            token: body.token || 'autogenerated'
        });
    }
};
